//---------------------------------------------------------------------------

#ifndef frmMainH
#define frmMainH
//---------------------------------------------------------------------------
#include "myinternet.h"
#include "chatserver.h"
#include "pmsForm.h"
#include "cgrbutton.h"                    
#include "sensor.h"
#include "sensortab.h"
#include "ShockwaveFlashObjects_OCX.h"
#include <AppEvnts.hpp>
#include <ComCtrls.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Grids.hpp>
#include <jpeg.hpp>
#include <Menus.hpp>
#include <OleCtrls.hpp>
#include <StdCtrls.hpp>
#include <ComCtrls.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Grids.hpp>
#include <jpeg.hpp>
#include <Menus.hpp>
#include <OleCtrls.hpp>
#include <StdCtrls.hpp>
#include "sensor.h"
#include "sensortab.h"
#include "cgrbutton.h"                 
#include <AppEvnts.hpp>
#include <ComCtrls.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Grids.hpp>
#include <jpeg.hpp>                               
#include <Menus.hpp>
#include <OleCtrls.hpp>                                       
#include <StdCtrls.hpp>                     
#include <Classes.hpp>
float Version = 0.997/47; // 47 is kinda masking
#define TestVersion false //only for moderators
#define VERSION FloatToStrF(Version*47,ffFixed,10,3)
//---------------------------------------------------------------------------
class Tmain : public TForm
{
__published:	// IDE-managed Components
        TLabel *welcome;
        TApplicationEvents *app;
        TPageControl *pages;
        TTabSheet *tablogin;
        TTabSheet *tabchat;
        TImage *Image2;
        TEdit *ednick;
        TEdit *edpass;
        TImage *Image4;
        TTimer *loginTmr;
        TTabSheet *tabregister;
        TEdit *edaccnick;
        TEdit *edaccpass;
        TEdit *edaccpass2;
        TEdit *edaccemail;
        TEdit *edaccemail2;
        TTabSheet *tabcarselect;
        TImage *Image6;
        TTabSheet *tabtos;
        TImage *Image7;
        TMemo *mess;
        TLabel *roomname;
        TRichEdit *chat;
        TStringGrid *inroom;
        TTabSheet *tabmain;
        TMainMenu *TestsMenu;
        TMenuItem *Tests;
        TMenuItem *Newaccount1;
        TMenuItem *Login1;
        TTabSheet *tabracestart;
        TMenuItem *Racetrack1;
        TTabSheet *tabcomputerselect;
        TTabSheet *tabsetbracket;
        TEdit *edbracket;
        TLabel *Label1;
        TGrButton *btngorace;
        TTimer *GameTimer;
        TTabSheet *tabrace;
        TShockwaveFlash *flupview;
        TShockwaveFlash *flstaging;
        TShockwaveFlash *flroad;
        TGrButton *btngotomain;
        TMenuItem *Racetrackonline1;
        TTabSheet *tabselectracer;
        TStringGrid *racers;
        TGrButton *btnselectracer;
        TTabSheet *tabchallengeselect;
        TLabel *Label2;
        TGrButton *btnBracket;
        TGrButton *btnHeadsUp;
        TTabSheet *tabwagerselect;
        TGrButton *btnForFun;
        TGrButton *btnWager;
        TEdit *edWager;
        TLabel *Label3;
        TLabel *lbAccount;
        TEdit *edOnlineBracket;
        TLabel *Label4;
        TLabel *Label5;
        TTabSheet *tabchallenges;
        TMenuItem *Challenges1;
        TMenuItem *Challengesanother1;
        TMenuItem *anotheranswerbuilderchallenge1;
        TTabSheet *tabanswer;
        TLabel *Label12;
        TGrButton *btnAnswerBracket;
        TEdit *edAnswerBracket;
        TPageControl *pageschallenges;
        TTabSheet *tabincoming;
        TTabSheet *taboutgoing;
        TPopupMenu *HotkeysMenu;
        TMenuItem *SpeedUp;
        TMenuItem *SpeedDown;
        TMenuItem *N1;
        TMenuItem *ChatSelectRoom1;
        TMenuItem *ChatCreateRoom1;
        TPanel *toppanel;
        TImage *Image1;
        TImage *rmain;
        TSensor *btnmaintab;
        TImage *Image9;
        TSensor *btnchat;
        TSensor *btnracetrack;
        TImage *Image12;
        TSensor *btnlogin;
        TImage *Image16;
        TSensor *btnregister;
        TImage *Image17;
        TSensor *btnforgot;
        TImage *Image18;
        TSensor *btnselectveh;
        TImage *Image19;
        TSensor *btnvehback;
        TImage *Image20;
        TSensor *Sensor3;
        TImage *Image21;
        TSensor *btncreate;
        TImage *Image22;
        TSensor *registerback;
        TImage *Image23;
        TSensor *Sensor6;
        TImage *Image24;
        TSensor *btnsend;
        TImage *Image25;
        TSensor *btnroom;
        TImage *Image26;
        TLabel *Label6;
        TMenuItem *Chatchat1;
        TTabSheet *tabaccount;
        TLabel *Label7;
        TLabel *Label17;
        TLabel *Label18;
        TLabel *Label19;
        TMenuItem *N2;
        TMenuItem *Accountcheck1;
        TLabel *Label20;
        TMenuItem *Create1;
        TMenuItem *Createchallengebuilderanotherheadsupwager11;
        TLabel *lbChatVersion;
        TLabel *lbRacersInRoom;
        TMenuItem *ChatPMS1;
        TMenuItem *Chatcolors1;
        TLabel *lbLoginVersion;
        TMenuItem *N3;
        TMenuItem *Peopleinroomloginmanypeople1;
        TComboBox *gender;
        TSensor *btnnotagree;
        TImage *Image29;
        TSensor *btnagree;
        TImage *Image30;
        TSensor *Sensor5;
        TImage *Image31;
        TMemo *tos;
        TSensorTab *SensorTab1;
        TSensorTab *SensorTab2;
        TSensorTab *SensorTab3;
        TSensorTab *SensorTab4;
        TSensorTab *SensorTab5;
        TSensorTab *SensorTab6;
        TSensorTab *SensorTab7;
        TSensorTab *SensorTab8;
        TSensorTab *SensorTab9;
        TSensorTab *SensorTab10;
        TSensorTab *SensorTab11;
        TSensorTab *SensorTab12;
        TSensorTab *SensorTab13;
        TSensorTab *SensorTab14;
        TMenuItem *ModeratorTools;
        TMenuItem *Moderatorwindowshow1;
        TPopupMenu *ModerMenu;
        TMenuItem *chatkick;
        TMenuItem *chatkickban;
        TMenuItem *Loginanothernonmoder1;
        TMenuItem *Loginbuildermoderkickanother1;
        TMenuItem *chatkickgameban;
        TMenuItem *Dummypagenext1;
        TMenuItem *Dummypreviouspage1;
        TMenuItem *Dummy1;
        TMenuItem *Dummy2;
        TMenuItem *Createfoulchallengefrombuildertoanother1;
        TMenuItem *falsestart;
        TMenuItem *Chatenter1;
        TMenuItem *Chatenterandflood1;
        TTimer *TestFloodTimer;
        TTimer *ChallengeBlink;
        TMenuItem *Startchallengeandfoul1;
        TTimer *FoulQuitRaceTimer;
        TMenuItem *Checkingprotection1;
        TMenuItem *Race1;
        TMenuItem *Racefalsestart1;
        TStringGrid *racerssearch;
        TEdit *edracersearch;
        TMenuItem *Racerssearch1;
        TGrButton *incomingresults;
        TGrButton *outgoingresults;
        TMenuItem *Race2;
        TMenuItem *Challenge1;
        TSensor *btnteam;
        TImage *Image10;
        TTabSheet *tabteam;
        TStringGrid *teamlist;
        TMenuItem *Team1;
        TMenuItem *Tabteam1;
        TStringGrid *race_teamsearch;
        TEdit *race_edteamsearch;
        TStringGrid *race_teammembers;
        TLabel *Label27;
        TStringGrid *teammoney;
        TLabel *lbteammoney;
        TLabel *Label28;
        TLabel *Label29;
        TPanel *pannoteam;
        TEdit *edteamsearch;
        TStringGrid *teamsearch;
        TStringGrid *teammembers;
        TLabel *Label23;
        TLabel *lbjoinrequests;
        TStringGrid *userjoinrequests;
        TGrButton *btnjointeam;
        TGrButton *btnapplytojoin;
        TGrButton *btncreateteam;
        TGrButton *btnteamchallenge;
        TPageControl *teamchallenges_pages;
        TTabSheet *team_incoming;
        TTabSheet *team_outgoing;
        TTabSheet *team_active;
        TTabSheet *team_completed;
        TStringGrid *teamchallenges;
        TMenuItem *Login2;
        TMenuItem *Tabteammember011;
        TLabel *Label30;
        TLabel *Label31;
        TLabel *Label32;
        TLabel *Label33;
        TImage *Image32;
        TSensor *btndealer;
        TTabSheet *tabdealer;
        TStringGrid *CarList;
        TLabel *Label34;
        TMenuItem *Dealer1;
        TLabel *lbBuyCarAccount;
        TLabel *lbDealerAccount;
        TSensor *btngarage;
        TImage *Image33;
        TTabSheet *tabgarage;
	TStringGrid *garageGrid;
        TLabel *lbgaragecarname;
        TLabel *Label36;
        TGrButton *btnsellcar;
        TLabel *Label35;
        TLabel *lbgarageaccount;
        TLabel *Label37;
        TGrButton *btnselectcar;
        TLabel *lbgaragecarparams;
        TTabSheet *tabshop;
        TSensor *Sensor1;
        TImage *Image34;
        TStringGrid *shopparts;
        TGrButton *btnbuypart;
        TLabel *Label38;
        TLabel *lbshopaccount;
        TLabel *lbpartchars;
        TLabel *lbpartname;
        TGrButton *btnmodify;
        TTabSheet *tabmodifications;
        TLabel *Label39;
        TStringGrid *carparts;
        TLabel *Label40;
        TGrButton *btninstall;
        TLabel *lbmodchars;
        TLabel *lbupgrade;
        TTabSheet *tabmaintenance;
        TGrButton *btnmaintenance;
        TGrButton *btnrefill;
        TLabel *Label41;
        TLabel *lbnitrousleft;
        TLabel *Label43;
        TLabel *lbnitrouscost;
        TLabel *Label45;
        TLabel *lbnitrousaccount;
        TLabel *lbnitromessage;
        TLabel *Label42;
        TGrButton *btnteamsearch;
        TGrButton *btnjointeamsearch;
        TGrButton *btnHideIncoming;
        TGrButton *btnHideOutgoing;
        TLabel *Label22;
        TLabel *Label26;
        TLabel *Label44;
        TStringGrid *racercars;
        TLabel *lbracercar;
        TLabel *lbracerstats;
		TTabSheet *tabchallenge;
        TLabel *lbchallengeracerstats;
        TGrButton *btnchallenge;
        TGrButton *btnAnswerChallenge;
        TGrButton *btnDeclineChallenge;
        TLabel *lbteamleaderhelp;
        TImage *chatuser;
        TImage *chatline;
        TLabel *Label46;
        TLabel *Label47;
        TGrButton *btnPinkSlip;
        TLabel *Label48;
        TLabel *lbjoin_teamstats;
        TLabel *lbrace_teamstats;
        TTimer *SmokemTimer;
        TLabel *Label49;
        TMenuItem *ModTools1;
        TMenuItem *N4;
        TLabel *lbMainVersion;
        TGrButton *btngearratios;
        TLabel *lbmagicgearmessage;
        TImage *chatmember;
	TImage *chatmoder;
        TImage *chatover;
        TTimer *durus;
        TLabel *Label50;
        TImage *Image35;
        TImage *Image36;
        TImage *Image37;
        TImage *Image38;
        TTabSheet *tabloading;
        TImage *Image39;
        TMenuItem *Gotochat1;
        TMenuItem *Quit1;
        TImage *Image40;
        TImage *Image41;
        TImage *Image42;
        TImage *Image43;
        TImage *Image44;
        TImage *Image45;
        TImage *Image46;
        TImage *Image47;
        TImage *Image48;
        TImage *Image50;
        TImage *Image51;
        TImage *Image52;
        TImage *Image53;
        TImage *Image54;
        TImage *Image49;
        TImage *Image55;
        TImage *Image56;
        TImage *Image57;
        TGrButton *GrButton1;
        TGrButton *btndeposit;
        TGrButton *btndistributefunds;
        TGrButton *btnbuycar;
        TMenuItem *ShowMessage1;
        TMenuItem *challenginfo1;
        TLabel *lbnoprivates;
        TLabel *lbnosound;
        TGrButton *repair;
        TLabel *lbenginedamage;
        TGrButton *reset;
	TLabel *Label54;
	TMenuItem *Help1;
	TTimer *autologin_tmr;
	TEdit *message_edt;
	TLabel *Label55;
	TLabel *Label57;
	TImage *Image8;
	TImage *ChallengesHighlight;
	TImage *Image28;
	TSensor *btnchallenges;
	TPanel *bottompanel;
	TImage *Image27;
	TSensor *btnaccount;
	TImage *Image13;
	TImage *selectedcarhint;
	TSensor *membership;
	TImage *Image67;
	TSensorTab *SensorTab15;
	TGrButton *btnchangepass;
	TEdit *ednewpassconfirm;
	TEdit *ednewpass;
	TEdit *edcurpass;
	TLabel *lbNick;
	TLabel *lbModifyAccountBallance;
	TLabel *lbstats;
	TLabel *lbmember;
	TLabel *lbrank;
	TCheckBox *cbnoprivates;
	TCheckBox *cbnosound;
	TLabel *lbchallenges;
	TImage *Image68;
	TLabel *RoomNameLabel;
	TImage *Image5;
	TLabel *Label59;
	TLabel *Label60;
	TLabel *Label61;
	TLabel *Label62;
	TLabel *Label63;
	TLabel *Label64;
	TSensorTab *SensorTab17;
	TSensor *Sensor7;
	TImage *Image69;
	TSensorTab *SensorTab18;
	TSensor *Sensor8;
	TImage *Image70;
	TSensorTab *dummytabstop;
	TImage *Image71;
	TSensor *Sensor4;
	TImage *Image65;
	TSensorTab *SensorTab16;
	TSensor *Sensor10;
	TImage *Image72;
	TSensorTab *SensorTab19;
	TPanel *IncomingPanel;
	TPanel *outgoingpanel;
	TImage *Image11;
	TImage *Image73;
	TLabel *Label13;
	TLabel *Label14;
	TLabel *Label15;
	TLabel *Label16;
	TLabel *Label56;
	TStringGrid *incoming_grid;
	TSensorTab *SensorTab20;
	TImage *Image74;
	TSensor *Sensor11;
	TSensor *Sensor12;
	TImage *Image75;
	TSensorTab *SensorTab21;
	TSensor *challengebutton;
	TImage *Image76;
	TSensorTab *SensorTab22;
	TSensor *resultsbutton;
	TImage *Image77;
	TSensorTab *SensorTab23;
	TSensor *hideresultsbutton;
	TImage *Image78;
	TSensorTab *SensorTab24;
	TLabel *yourresult_lbl;
	TLabel *opponentresult_lbl;
	TSensor *Sensor13;
	TImage *Image79;
	TSensorTab *SensorTab25;
	TSensor *incoming_button;
	TImage *Image80;
	TSensorTab *SensorTab26;
	TStringGrid *outgoing;
	TSensor *outgoingresults_button;
	TSensorTab *SensorTab27;
	TImage *Image81;
	TImage *Image82;
	TSensorTab *SensorTab28;
	TSensor *hideoutgoing_button;
	TLabel *outgoingresult_lbl;
	TLabel *outgoingresult2_lbl;
	TLabel *Label8;
	TLabel *Label9;
	TLabel *Label10;
	TLabel *Label11;
	TLabel *Label58;
	TTabSheet *tabteammanage;
	TPanel *teammanage_panel;
	TImage *Image83;
	TNotebook *team_nb;
	TStringGrid *sgteammess;
	TLabel *Label51;
	TLabel *Label52;
	TLabel *Label53;
	TGrButton *teammess_post;
	TGrButton *teammess_edit;
	TGrButton *teammess_del;
	TSensor *Sensor14;
	TImage *Image66;
	TSensorTab *SensorTab29;
	TSensor *Sensor15;
	TImage *Image84;
	TSensorTab *SensorTab30;
	TImage *Image85;
	TSensorTab *SensorTab31;
	TSensor *Sensor16;
	TImage *Image86;
	TSensor *Sensor17;
	TSensorTab *SensorTab32;
	TImage *Image87;
	TSensor *Sensor18;
	TSensorTab *SensorTab33;
	TLabel *lbTeamName;
	TLabel *Label24;
	TLabel *Label25;
	TGrButton *btnremovemember;
	TGrButton *btnacceptjoin;
	TGrButton *btndeclinejoin;
	TStringGrid *teamteammembers;
	TStringGrid *teamjoinrequests;
	TGrButton *btnquitteam;
	TLabel *lbteamstats;
	TImage *chatadmin;
	TShockwaveFlash *flgarage;
	TTimer *garagetimer;
	TShockwaveFlash *flchallenge;
	TTimer *selectracertimer;
	TLabel *lbracername;
	TShockwaveFlash *flchallengebadges;
	TShockwaveFlash *flaccountbadges;
	TImage *chatfmod;
	TShockwaveFlash *flchallengecar;
	TShockwaveFlash *flchallengeanswercar;
	TShockwaveFlash *flcarreg;
	TShockwaveFlash *fldealer;
	TShockwaveFlash *flmodcar;
	TShockwaveFlash *flmaintcar;
	TShockwaveFlash *flselected;
	TStringGrid *registercarlist;
        void __fastcall loginTmrTimer(TObject *Sender);
        void __fastcall sendClick(TObject *Sender);
        void __fastcall FormDestroy(TObject *Sender);
        void __fastcall messKeyPress(TObject *Sender, char &Key);
        void __fastcall appException(TObject *Sender,
          Exception *E);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall roomlistClick(TObject *Sender);
        void __fastcall inroomupdateClick(TObject *Sender);
        void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall btnloginClick(TObject *Sender);
        void __fastcall btnforgotClick(TObject *Sender);
        void __fastcall btncancelClick(TObject *Sender);
        void __fastcall btnsendpassClick(TObject *Sender);
        void __fastcall btncreateClick(TObject *Sender);
        void __fastcall btnregisterClick(TObject *Sender);
        void __fastcall btnhaveaccountClick(TObject *Sender);
        void __fastcall btnvehbackClick(TObject *Sender);
        void __fastcall btnselectvehClick(TObject *Sender);
        void __fastcall btnnotagreeClick(TObject *Sender);
        void __fastcall btnagreeClick(TObject *Sender);
        void __fastcall edpassKeyPress(TObject *Sender, char &Key);
        void __fastcall inroomDblClick(TObject *Sender);
        void __fastcall btnchatClick(TObject *Sender);
        void __fastcall Image10Click(TObject *Sender);
        void __fastcall appActivate(TObject *Sender);
        void __fastcall appDeactivate(TObject *Sender);
        void __fastcall Newaccount1Click(TObject *Sender);
        void __fastcall Login1Click(TObject *Sender);
        void __fastcall btnracetrackClick(TObject *Sender);
        void __fastcall Racetrack1Click(TObject *Sender);
        void __fastcall btncomputerchallengeClick(TObject *Sender);
        void __fastcall btncomputertwoClick(TObject *Sender);
        void __fastcall btngoraceClick(TObject *Sender);
        void __fastcall GameTimerTimer(TObject *Sender);
        void __fastcall btngotomainClick(TObject *Sender);
        void __fastcall Racetrackonline1Click(TObject *Sender);
        void __fastcall btnOnlineChallengeClick(TObject *Sender);
        void __fastcall btnselectracerClick(TObject *Sender);
        void __fastcall btnBracketClick(TObject *Sender);
        void __fastcall btnForFunClick(TObject *Sender);
        void __fastcall btnchallengesClick(TObject *Sender);
        void __fastcall Challenges1Click(TObject *Sender);
        void __fastcall Challengesanother1Click(TObject *Sender);
        void __fastcall anotheranswerbuilderchallenge1Click(
          TObject *Sender);
        void __fastcall btnAnswerChallengeClick(TObject *Sender);
        void __fastcall btnAnswerBracketClick(TObject *Sender);
        void __fastcall btnpracticeClick(TObject *Sender);
        void __fastcall SpeedUpClick(TObject *Sender);
        void __fastcall SpeedDownClick(TObject *Sender);
        void __fastcall ChatSelectRoom1Click(TObject *Sender);
        void __fastcall ChatCreateRoom1Click(TObject *Sender);
        void __fastcall Chatchat1Click(TObject *Sender);
        void __fastcall btnaccountClick(TObject *Sender);
        void __fastcall btnchangepassClick(TObject *Sender);
        void __fastcall Accountcheck1Click(TObject *Sender);
        void __fastcall btncomputeroneClick(TObject *Sender);
        void __fastcall btnWagerClick(TObject *Sender);
        void __fastcall Create1Click(TObject *Sender);
        void __fastcall btnHeadsUpClick(TObject *Sender);
        void __fastcall Createchallengebuilderanotherheadsupwager11Click(
          TObject *Sender);
        void __fastcall ChatPMS1Click(TObject *Sender);
        void __fastcall Chatcolors1Click(TObject *Sender);
        void __fastcall inroomDrawCell(TObject *Sender, int ACol, int ARow,
          TRect &Rect, TGridDrawState State);
        void __fastcall registerbackClick(TObject *Sender);
        void __fastcall ModeratorToolsClick(TObject *Sender);
        void __fastcall Moderatorwindowshow1Click(TObject *Sender);
        void __fastcall Loginanothernonmoder1Click(TObject *Sender);
        void __fastcall chatkickClick(TObject *Sender);
        void __fastcall chatkickbanClick(TObject *Sender);
        void __fastcall chatkickgamebanClick(TObject *Sender);
        void __fastcall Createfoulchallengefrombuildertoanother1Click(
          TObject *Sender);
        void __fastcall Chatenter1Click(TObject *Sender);
        void __fastcall Chatenterandflood1Click(TObject *Sender);
        void __fastcall TestFloodTimerTimer(TObject *Sender);
        void __fastcall appMessage(tagMSG &Msg, bool &Handled);
        void __fastcall OnServerSystemMessages(TObject *Sender);
        void __fastcall ChallengeBlinkTimer(TObject *Sender);
        void __fastcall Startchallengeandfoul1Click(TObject *Sender);
        void __fastcall FoulQuitRaceTimerTimer(TObject *Sender);
        void __fastcall Checkingprotection1Click(TObject *Sender);
        void __fastcall Race1Click(TObject *Sender);
        void __fastcall Racefalsestart1Click(TObject *Sender);
        void __fastcall Racerssearch1Click(TObject *Sender);
        void __fastcall edracersearchChange(TObject *Sender);
        void __fastcall edracersearchKeyPress(TObject *Sender, char &Key);
        void __fastcall incomingresultsClick(TObject *Sender);
        void __fastcall incoming_gridClick(TObject *Sender);
        void __fastcall outgoingresultsClick(TObject *Sender);
        void __fastcall outgoingClick(TObject *Sender);
        void __fastcall inroomMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall edaccnickChange(TObject *Sender);
        void __fastcall chatMouseWheel(TObject *Sender, TShiftState Shift,
          int WheelDelta, TPoint &MousePos, bool &Handled);
        void __fastcall btnteamClick(TObject *Sender);
        void __fastcall btncreateteamClick(TObject *Sender);
        void __fastcall Tabteam1Click(TObject *Sender);
        void __fastcall edteamsearchChange(TObject *Sender);
        void __fastcall tabteamShow(TObject *Sender);
        void __fastcall btnquitteamClick(TObject *Sender);
        void __fastcall btnjointeamClick(TObject *Sender);
        void __fastcall teamsearchDblClick(TObject *Sender);
        void __fastcall userjoinrequestsClick(TObject *Sender);
        void __fastcall btnacceptjoinClick(TObject *Sender);
        void __fastcall btndeclinejoinClick(TObject *Sender);
        void __fastcall btnapplytojoinClick(TObject *Sender);
        void __fastcall teamteamShow(TObject *Sender);
        void __fastcall teamraceShow(TObject *Sender);
        void __fastcall btnremovememberClick(TObject *Sender);
        void __fastcall teamteammembersClick(TObject *Sender);
        void __fastcall teamfundsShow(TObject *Sender);
        void __fastcall btndepositClick(TObject *Sender);
        void __fastcall btndistributefundsClick(TObject *Sender);
        void __fastcall btnteamchallengeClick(TObject *Sender);
        void __fastcall teamchallengeShow(TObject *Sender);
        void __fastcall team_incomingShow(TObject *Sender);
        void __fastcall teamchallengesDblClick(TObject *Sender);
        void __fastcall Login2Click(TObject *Sender);
        void __fastcall Tabteammember011Click(TObject *Sender);
        void __fastcall edbracketKeyUp(TObject *Sender, WORD &Key,
          TShiftState Shift);
        void __fastcall btndealerClick(TObject *Sender);
        void __fastcall tabdealerShow(TObject *Sender);
        void __fastcall CarListClick(TObject *Sender);
        void __fastcall Dealer1Click(TObject *Sender);
        void __fastcall btngarageClick(TObject *Sender);
        void __fastcall btnbuycarClick(TObject *Sender);
        void __fastcall tabgarageShow(TObject *Sender);
        void __fastcall garageGridClick(TObject *Sender);
        void __fastcall btnsellcarClick(TObject *Sender);
        void __fastcall FormShow(TObject *Sender);
        void __fastcall tabcarselectShow(TObject *Sender);
        void __fastcall registercarlistClick(TObject *Sender);
        void __fastcall btnselectcarClick(TObject *Sender);
        void __fastcall Sensor1Click(TObject *Sender);
        void __fastcall tabshopShow(TObject *Sender);
        void __fastcall shoppartsClick(TObject *Sender);
        void __fastcall btnmodifyClick(TObject *Sender);
        void __fastcall tabmodificationsShow(TObject *Sender);
        void __fastcall btnbuypartClick(TObject *Sender);
        void __fastcall btninstallClick(TObject *Sender);
        void __fastcall carpartsClick(TObject *Sender);
        void __fastcall btnmaintenanceClick(TObject *Sender);
        void __fastcall tabmaintenanceShow(TObject *Sender);
        void __fastcall btnrefillClick(TObject *Sender);
        void __fastcall btnDeclineChallengeClick(TObject *Sender);
        void __fastcall race_edteamsearchKeyPress(TObject *Sender,
          char &Key);
        void __fastcall btnteamsearchClick(TObject *Sender);
        void __fastcall btnjointeamsearchClick(TObject *Sender);
        void __fastcall edteamsearchKeyPress(TObject *Sender, char &Key);
        void __fastcall teamjoinrequestsClick(TObject *Sender);
        void __fastcall smokemClick(TObject *Sender);
        void __fastcall blockClick(TObject *Sender);
		void __fastcall tabchallengesShow(TObject *Sender);
        void __fastcall btnHideIncomingClick(TObject *Sender);
        void __fastcall tabaccountShow(TObject *Sender);
        void __fastcall racerssearchClick(TObject *Sender);
        void __fastcall racercarsClick(TObject *Sender);
        void __fastcall tabselectracerShow(TObject *Sender);
        void __fastcall tabchallengeShow(TObject *Sender);
        void __fastcall btnchallengeClick(TObject *Sender);
        void __fastcall btnPinkSlipClick(TObject *Sender);
        void __fastcall race_teamsearchClick(TObject *Sender);
        void __fastcall teamsearchClick(TObject *Sender);
        void __fastcall topsDblClick(TObject *Sender);
        void __fastcall SmokemTimerTimer(TObject *Sender);
        void __fastcall tabwagerselectShow(TObject *Sender);
        void __fastcall tabmainShow(TObject *Sender);
        void __fastcall btngearratiosClick(TObject *Sender);
        void __fastcall garageGridDrawCell(TObject *Sender, int ACol, int ARow,
          TRect &Rect, TGridDrawState State);
        void __fastcall durusTimer(TObject *Sender);
        void __fastcall membershipClick(TObject *Sender);
        void __fastcall topteamsClick(TObject *Sender);
        void __fastcall topracersClick(TObject *Sender);
        void __fastcall fastestcarsClick(TObject *Sender);
        void __fastcall tabloginShow(TObject *Sender);
        void __fastcall Quit1Click(TObject *Sender);
        void __fastcall Gotochat1Click(TObject *Sender);
        void __fastcall ShowMessage1Click(TObject *Sender);
        void __fastcall challenginfo1Click(TObject *Sender);
        void __fastcall lbnoprivatesClick(TObject *Sender);
        void __fastcall cbnoprivatesClick(TObject *Sender);
        void __fastcall cbnosoundClick(TObject *Sender);
        void __fastcall lbnosoundClick(TObject *Sender);
        void __fastcall tabteammessShow(TObject *Sender);
        void __fastcall sgteammessClick(TObject *Sender);
        void __fastcall teammess_postClick(TObject *Sender);
        void __fastcall teammess_editClick(TObject *Sender);
        void __fastcall teammess_delClick(TObject *Sender);
        void __fastcall repairClick(TObject *Sender);
        void __fastcall resetClick(TObject *Sender);
	void __fastcall Help1Click(TObject *Sender);
	void __fastcall autologin_tmrTimer(TObject *Sender);
	void __fastcall tabracestartShow(TObject *Sender);
	void __fastcall Sensor12Click(TObject *Sender);
	void __fastcall incoming_buttonClick(TObject *Sender);
	void __fastcall Sensor14Click(TObject *Sender);
	void __fastcall Sensor15Click(TObject *Sender);
	void __fastcall Sensor16Click(TObject *Sender);
	void __fastcall Sensor17Click(TObject *Sender);
	void __fastcall Sensor18Click(TObject *Sender);
	void __fastcall team_nbPageChanged(TObject *Sender);
	void __fastcall garagetimerTimer(TObject *Sender);
	void __fastcall selectracertimerTimer(TObject *Sender);
	void __fastcall registercarlistDrawCell(TObject *Sender, int ACol, int ARow,
          TRect &Rect, TGridDrawState State);
private:	// User declarations
public:		// User declarations
        __fastcall Tmain(TComponent* Owner);
        AnsiString smokemnick; // used in smokem timer
        cChatServer Server;
        //AnsiString nick;
        bool Closing;
        TIniFile* ini;
        TList* PMS;
        void SelectPage(TTabSheet* newpage);
        Tpms* PMSForm(AnsiString withnick);
        TStringList* PrivatesWaiting;
        bool AppActive;
        void marknewmessage(AnsiString nick);
        void unmarknewmessage(AnsiString nick);
        void __fastcall PMSActivate(TObject* Sender);
        TColor chatcolor(AnsiString nickortext,bool admin,bool moder, bool supermod, bool member, bool female);
        void __fastcall OnChatMessage(TObject *Sender);
        void FillChallenges();
        void FillUserRequests();
        void FillTeamRequests();
        void FillTeams(AnsiString part);
};
//---------------------------------------------------------------------------
extern PACKAGE Tmain *main;
//---------------------------------------------------------------------------
#endif
